spring:
  application:
    name: Outdoors Server
  output:
    ansi:
      enabled: always
  profiles:
    active: local
#  main:
#    allow-bean-definition-overriding: true

server:
    port: 8080
    #port: 80
    servlet:
        register-default-servlet: true
        encoding:
            enabled: true
            charset: UTF-8
    tomcat:
        additional-tld-skip-patterns: oraclepki.jar, osdt_core.jar, osdt_cert.jar

nexacro:
    main: 
        path: /static/vue/index.html
    exception:
        default.message: fail.common.msg

springdoc:
    version: 'v1'
    api-docs:
        enabled: true
        group:
            enabled: true
            ## default path: /v3/api-docs
            path: /api-docs
    swagger-ui:
        path: /swagger
        display-request-duration: true
        groups-order: DESC
        operations-sorter: alpha
        tags-sorter: alpha
        disable-swagger-default-url: true
    show-actuator: true
    group-configs:
        - group: wms
          paths-to-match: /sample/**
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

logging:
  config: classpath:logback-spring.xml
  file:
    path: /app/logs
    name: was-log