spring:
  application:
    name: OYWMS Local Server
  output:
    ansi:
      enabled: always

  datasource:
    hikari:
      master:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        jdbc-url: jdbc:log4jdbc:mariadb://database-1.cl1qpbs1xffv.ap-northeast-2.rds.amazonaws.com/odthdb
        username: admin
        password: lkt1234!
        minimumIdle: 10
        maximumPoolSize: 100
        maxLifetime: 3540000
        mybatis:
          config-location: classpath:mybatis-config-master.xml
    #    auto-commit: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  web:
    resources:
      chain:
        cache: false
        strategy:
          content:
            paths: /nexa/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

upload:
  temp:
    down-path: /download/temp
    up-path: D:/upload/temp
  ops:
    down-path: /download/ops
    up-path: D:/upload/ops

odth:
  board:
    default-pass: 0000